/**
 * icons.ts — one drawn set, at one weight, 24x24, 1.7px stroke.
 *
 * Unicode glyphs come from five different type designers and sit on five
 * different baselines; a sidebar built from them reads as a ransom note.
 */
const svg = (d: string) =>
  `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"
        stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;

export const icon = {
  identity: svg('<circle cx="12" cy="8.5" r="3.8"/><path d="M4.8 20a7.2 7.2 0 0 1 14.4 0"/>'),
  reach: svg('<circle cx="12" cy="12" r="2.6"/><path d="M7.4 7.4a6.5 6.5 0 0 0 0 9.2M16.6 16.6a6.5 6.5 0 0 0 0-9.2"/><path d="M4.2 4.2a11 11 0 0 0 0 15.6M19.8 19.8a11 11 0 0 0 0-15.6"/>'),
  profile: svg('<path d="M5 4.5h14v15H5z"/><path d="M8.5 9h7M8.5 12.5h7M8.5 16h4"/>'),
  register: svg('<circle cx="9" cy="8.5" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0"/><path d="M16 6.5h5M16 10h5M16 13.5h3"/>'),
  check: svg('<path d="M4.5 12.5l5 5 10-11"/>'),
  claimed: svg('<circle cx="12" cy="12" r="8.5"/><path d="M12 8v4.5M12 16h.01"/>'),
  copy: svg('<rect x="8.5" y="8.5" width="11" height="11" rx="2"/><path d="M15.5 8.5v-2a2 2 0 0 0-2-2h-7a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h2"/>'),
  search: svg('<circle cx="11" cy="11" r="6"/><path d="M20 20l-4.5-4.5"/>'),
  close: svg('<path d="M6 6l12 12M18 6L6 18"/>'),
  spark: svg('<path d="M12 3.5l2 6.5 6.5 2-6.5 2-2 6.5-2-6.5L3.5 12l6.5-2z"/>'),
};

/**
 * The mark: a mask, drawn as the contract draws one.
 *
 * A visor over a face, which is what every generated mask in this app is. It is
 * ours because the artwork is generated by our own contract, not because of the
 * shape: anybody can copy an outline, nobody can copy the chain that mints it.
 */
export const logo = (size = 24) => `
<svg width="${size}" height="${size}" viewBox="0 0 32 32" fill="none" aria-hidden="true">
  <rect x="6" y="4" width="20" height="24" rx="6" stroke="currentColor" stroke-width="2"/>
  <rect x="9.5" y="12" width="13" height="6" rx="3" fill="currentColor"/>
  <path d="M16 4V1.5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
  <circle cx="16" cy="1.5" r="1.5" fill="currentColor"/>
</svg>`;
